### ISSUE TITLE
ParFlow result data

### ISSUE THREAD

**Issue by Kenichiro-Yoshimi** [Kitware/paraview-flow#5]
Is it possible to share sample data such as **washita.pfmetadata** or **LW.out.pfmetadata**?

**Comment by jourdain** [comment]
Just added a [metadata example](https://github.com/Kitware/paraview-flow/tree/master/sample-data) but you will need the actual data to have the viewer properly work. You may need to run [Parflow](https://github.com/parflow/parflow) to get the actual output of the washita run.

**Comment by Kenichiro-Yoshimi** [comment]
Thank you very much for your help. I'll take a look to ParFlow.
